### ISSUE TITLE
Financial Modeling Prep API

### ISSUE THREAD

**Issue by dudd9d92** [JoshuaR503/Stock-Market-App#4]
In the about section, you've mentioned "financial modeling prep API", but no where did you mention how to input API key for financialmodelingprep.com in /lib/keys/api_keys.dart, but mentioned in /lib/helpers/variables.dart .

**Comment by JoshuaR503** [comment]
@dudd9d92, thank you so much for letting me know about this issue. It seems like Financial Modeling Prep API now requires an API key. I will be pushing a new commit to address this issue.
