### ISSUE TITLE
PodFile issue

### ISSUE THREAD

**Issue by jasonjackson** [JoshuaR503/Stock-Market-App#5]
Curious if this is building for you?  Also if you have any idea on what is wrong in the PodFile? 

I'm pretty keen to checkout what you did with all of these API integrations, but am a little stuck getting it built.

Thanks!!

Error:

`
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: no implicit conversion of nil into String.

     #  from /Users/jason/development/projects/Stock-Market-App/ios/Podfile:57
     #  -------------------------------------------
     #      unless File.exist?(copied_framework_path)
     >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
     #      end
     #  -------------------------------------------

    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:318:in `rescue in block in from_ruby'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:312:in `block in from_ruby'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `new'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `from_ruby'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:276:in `from_file'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-1.10.0/lib/cocoapods/config.rb:205:in `podfile'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:46:in `run'
    /Users/jason/.gem/ruby/2.7.2/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /Users/jason/.gem/ruby/2.7.2/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /Users/jason/.gem/ruby/2.7.2/bin/pod:23:in `load'
    /Users/jason/.gem/ruby/2.7.2/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12 Pro Max.
`

**Comment by JoshuaR503** [comment]
Hi there! Sorry for the late response. I've fixed the error. I updated Flutter, a library and the Pod file. I followed the steps in [this Stackoverflow thread](https://stackoverflow.com/questions/59362862/flutter-ios-build-failed-an-error-of-pod-files-podfile-is-out-of-date/63506237#:~:text=Warning%3A%20Podfile%20is%20out%20of,Store%20submission%20rejection%20or%20crashes.&text=platforms%20for%20details.-,If%20you%20have%20local%20Podfile%20edits%20you%20would%20like%20to,%2Fissues%2F45197%20for%20instructions.). I also updated my iPhone 12 to the latest version. Remember to run `flutter build ios`. Let me know if the new fix works.

**Comment by JoshuaR503** [comment]
@jasonjackson, just wondering if you had viewed my answer and if the fix worked for you?

**Comment by jasonjackson** [comment]
@JoshuaR503 sorry for the delay, and appreciate your help!  I did take a minute and try to get this working last night, but am facing the following error:


```
Changing current working directory to: /Users/jason/development/projects/Stock-Market-App
Building com.stockmarket.app for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 2NJM8PU222
Running Xcode build...                                                  
Xcode build done.                                            3.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    error: No profiles for 'com.stockmarket.app' were found: Xcode couldn't find any iOS App Development provisioning profiles
    matching 'com.stockmarket.app'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing,
    pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')

Encountered error while building for device.
jason@Jasons-MacBook-Pro keys % 
```

I just wanted to give a quick response, but will spend some time googling and see if i can make sense of what is going on.  Again, thanks for your time.

**Comment by JoshuaR503** [comment]
@jasonjackson, it seems like this is an issue related to [code signing](https://help.apple.com/xcode/mac/current/#/dev80cc24546). [Try following this thread](https://stackoverflow.com/questions/65192512/flutter-error-no-profiles-for-xxx-were-found-xcode-couldn-t-find-any-ios-app).

**Comment by JoshuaR503** [comment]
Hey @jasonjackson, I'll close this issue since there are no new updates. Feel free to open a new one in case you need help!
